wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699746003.888805
    t:
      1:
      - 1
      - 5
      - 41
      - 51
      - 53
      - 55
      - 80
      2:
      - 1
      - 5
      - 41
      - 51
      - 53
      - 55
      - 80
      3:
      - 13
      - 23
      4: 3.10.13
      5: 0.15.12
      8:
      - 3
      - 5
      13: windows-amd64
batch_size:
  desc: null
  value: 4
num_workers:
  desc: null
  value: 8
optimizer:
  desc: null
  value: adam
learning_rate:
  desc: null
  value: 0.0001
